// Compressed Roster for TGMS Pegadapally (All 471 Students)
(function() {
  const data = [
    {
      c: "Class 6th - Section A", b: "6th",
      n: "ANNAMDAS KARTHIK VARMA|BEENAVENI HANSIKA|BOGA SATHWIK|BOGA VIGNESH|BURRA MANI DEEP|BYRA LAXMAN|BYRA RAM|CHINTHAPANDU RANADEEP|ERELLI ASHWITH|GUNTI NIRANJAN KUMAR|KALLEM SRIKANTH|KUNDELLA SAHARSHINI|MATETI HARI SHARAN|MATETI MURALI VARDHAN|MULKALA HIMANISH NANDHAN|PULLA DEEKSHITHA|RANGU REVANTH|SAMBARI GANESHWAR|SINGIREDDY VAMSHI KRISHNA REDDY|THADURI VISHWANJA"
    },
    {
      c: "Class 7th - Section A", b: "7th",
      n: "ANEEF PASHA|ARUKUTA SHASWANTH|BANOTH AMULYA|BATHINI KAARTHIKEYA|DAVANAPELLI SRI CHAITRA|GOLLAPALLY REYHWIKA|GUNDLAPELLI MAHALAXMI|KADALA RITHVIK|LINGAMPELLI MANASWITH|MANDHA MANOJ|MARIKANTI VINODHA|MARRIPELLI MAHESH|MULKA MANOJ KUMAR|MUTHYALA SAVIYA|NAGAM SAGARIKA|ODNALA MAHARSHITHA|PABBALA AKSHITH KUMAR|RAGALLA VINAY|THOTA JESHWANTH|VILASAGARAM KARTHIK"
    },
    {
      c: "Class 8th - Section A", b: "8th",
      n: "ADEPU VISHAL|AVUNOOTI HARSHITHA|BANDARI AKSHAYA|BANOTH LUCKY|BEDIGAM NISHANTH|BYRA SHIVA MALLIKARJUN|CHILUMULA DEEKSHITHA|DOBBALA PRATHIBA|DONTHARAVENI MANOHAR|DORAGANDLA KUMAR|DORAGANDLA RAMCHARAN|GOGULA GABBAR SINGH|JITTAVENI MANOJ|KOGILALA VAISHNAVI|KOGILALA VARSHA|KOMALLA LASYA|MANDA RAMCHARAN TEJA|MANDA SAI NIKHIL|SATHPADI VARUN|SEEGIRI ABHINAVA|SIGIRI NIROJ|THADAGONDA AKASH|THAMMALLA RAKESH KUMAR|THOTA HARI CHARAN|THOTLA MADHU"
    },
    {
      c: "Class 9th - Section A", b: "9th",
      n: "ADAPELLY PRAJWALA|AGURLA MANOHAR|AILAVENI SAHASRIKA|AJMEERA VARSHINI|AJMIRA AJAY|BANDAPELLY RISHI|BATHINI SATWIKA|BEKKAM SHIVA KUMAR|BERA NISHWANTH|BODDULA MANITEJ|BONAGIRI KEERTHI PRIYA|DONTHARAVENI MANICHANDU|EDELLI DISHA|ELLANKI GOUTHAM|ERAVENI VAISHNAVI|GADAM SRINIDI|GADHE VYSHNAVI|GANGADHARA SRUJANA|GANNEBOINA SRUTHI|GATTU GAGAN DHEEP|GOGULA PALLAVI|GONE ROHITH|GUDIVANDULA VICTORIA|GUMPULA VYSHNAVI|KALLEM SUSHANTH KUMAR|KANDHUKALA JASHUVA KUMAR|KASHETTI VISHNU|KATLA RISHITH|KOLIPAKA BENARJI|KOMMOJU VISHWANI|KOTA RANADHEER|KOTHURI KETHAN|KUDUDHULA ROHAN TEJA|MADDELA NEEHAL|MAGENI SHRAVYA|MAMIDIPALLI HARSHA|MANDA ABHIRAM|MARAMPELLI SATHWIK|NAKKA SHIVAKUMAR|NEDARI SINDHU|PITTALA SRI VARSHITHA|PULI KARTHIK|PUNNAM AVANTHIKA|RACHARLA SRAVAN KUMAR|SEEGIRI PRANAY KUMAR|THULLA MANU SRI|UPPU AKSHAY KUMAR|VILASAGARAM RISHI"
    },
    {
      c: "Class 9th - Section B", b: "9th",
      n: "ADIPELLY PRAVALIKA|AGURLA ARCHANA|AJMIRA VARSHINI|AJMIRA YUGENDAR|ARE SATWIKA|ARROJU PRAVASTHI|ARUKUTA RISHWANTH|BANOTH RAJESHWARI|BATHINI DEEKSHITHA|BEERLA AKSHARA|BEKKAM HANISH|BINAVENI HEMANTH|DOMMATI KARTHIK|DONAKONDA SHYAM KUMAR|GALIPELLY VISHNU TEJA|GANEBOINA HARSHA VARDHAN|GUGLOTHU KARTHIK|GUNDLAPELLY KETHESHWAR|JETTI MADHUMATHI|JETTI MAHESHWARI|KAMBALA ANUSHA|KARU RISHIKA|KOMALLA VIKAS|KOTHAPALLI ASHWITH KUMAR|KOTTURI THIRUMAL|KUNDELLA HARSHINI|LINGALA VARSHITHA|MADIGELA SAI HARSHITH|MALA AKSHAY KUMAR|MATETI GAYATRI|MODUMPALLY NAMAN TEJ|MOLOTH KAVYA|NADIMETLA PRANAV TEJA|NYATHA SAHITH|ORUGALA MANOJ|PALUMARU JANAJAGRUTHI|PANDUGA HEMALATHA|PATNURI GOUTHAM RAJ|RACHARLA HARSHAVARDHAN|RAGALLA SAHASRA|SAYYD IRFANA|SEEGIRI RUTHIK|SINGARAPU SHIVANJALI|SOORA SAI KUMAR|THATIPANDU SRI CHARAN|THODETI HARIKA|THOTA ASHWITH|THUMMANAPALLI HIMAJA|VARSHINI GANSH VANNAM"
    },
    {
      c: "Class 10th - Section A", b: "10th",
      n: "ADUPA AKSHITH|AILAVENI ARCHANA|AJMIRA SHIVANI|BALIJAPELLI VARSHINI|BANDARI VARUN GOUD|BATTULA SHRUTHI|BHAIRA RAMCHARAN|BHUSARAPU SRIHANI|BOGA RAVITEJA|BOMMENA SANTHOSH|BYRA SHARANYA|CHATARLA HARIKA|DANDU SRI HARSHA|DHAVANAPELLY HIMA SRI|DOBBALA LOKESH|ELAGANDULA SIDDATRHA|GAJJI AKSHAYA|GAJJI ASRITHA|GAJULA DIVYA SRI|GALIPELLI ADITHYA|GANNEBOINA GANGOTHRI|GUNTUKULA ESWER|KADALA RITHWIKA|KOLIPAKA AKSHARA|KORRI NIKHIL|KOTA CHAKRIKA|MALA SRIJA|MANDALA SRI KRUTHIKA|MARRIKANTI SAHASRA|MD HARSHIYA ANJUM|MERUGU SAI PRIYA|MULKA SAI KRISHNA|PEPARLA HARSHA VARDHAN|PUNNAM ALEKHYA|PUNNAM SANJANA|RONDLA SRISHANK REDDY|SAMBARI HARISHWAR|SEEGIRI ANANDI|SRIKOTI SAHITHI|THODETI NAVYASRI|THOTA VYSHNAVI|THUKUNTLA MARUTHI RAO|VELMULA SHARANYA"
    },
    {
      c: "Class 10th - Section B", b: "10th",
      n: "ADEPU VAISHNAVI|ADIGOPPULA ANUSH|ADUPA AKSHITH KUMAR|AMUDURTHI SRIVANI|BATHINI NIHARIKA|BEKKAM HARSHA VARDHAN|BODDULA SRI CHARAN|BODDULA SRI RAM|BOGA SRI HARSHINI|BYRA RISHITHA|CHATLA VIVEK|CHEVULA PRASHANTH|CHINTHAKINDHI NIHARIKA|DONTURAVENI AKSHAYA|DORAGANDLA ALEKYA|DUMMALA ASHWANTH|ENUGULA AKSHAYA|GAJJI VISHNU VARDHAN|GOKA MARUTHI|GOTLA SREEJA|GURIJALA LAKSHITHA|ITIKYALA ARAVIND|JETTI AKSHAYA|JITTAVENI PRANITH|KAMADRI AKSHITH|KASHETTI MANIDEEP|KODIDHELA VARSHITHA|KOLAPURI RISHVIK|KOLIPAKA GOUTHAM|KONTHAM HIMAVARSHINI|KYASA SAI CHARAN|MACHA KAVYA|MADDELA PAVANI|MALLARAPU NAVYASRI|NALUVALA KAVERI|PULI PRANAY TEJA|RAPELLY AVANTHIKA|SHIVARATHRI HARSHA|SUDAGONI RISHITH|THAMMALLA RANJITH KUMAR|THODETI SHASHI KUMAR|THUMMANAPELLY ASRITHA|UPPULANCHA HARSHITH|VUTKURI HARSHAVARDHAN REDDY"
    },
    {
      c: "Inter 1st Year (MPC)", b: "Inter 1st Year (MPC)",
      n: "ADIGOPPULA HARIKA|AJMIRA KEERTANA|ARE SRIJA|BADINENI SHIVA SAI|BANOTHU HARSHA|BATHINI CHARAN|BIYALA SAI NARSIMHA RAO|BUSA SAMANVI|DOMMATI VAMSHI|DOODAM MAHALAXMI|ELLENKI SATHWIKA|GAJURAVENI MAHESHWARI|GANANTHULA NITHISHA|GANNAVENI PALLAVI|GUDURI SIRI|GUNDAVENI LAYA|JAKKULA SRIKANTH|JITTAVENI SRI LEKHA|KALWALA SALONI|KANDI VAISHNAVI|KANDI YOGESH|KATLA DINESH|KEDAM SUKUMAR|KOLIPAKA ABHILASH|KOLIPAKA KAMALAKAR|KOTHA SRUTHIKA|KUNCHE ASHWITH|MATETI MYTHRI|NAGAM MADHAVI|NALUVALA JYOTHI|NAMPALLY SAHITHI|NAREDLA SAI REDDY|PALUMARU VARSHINI|POTHUGANTI SUPRIYA|RACHAKONDA RAMADASU|RAGALLA SIDDESH|RANGU JASHWANTH|THOTLA AMULYA|VARALA RISHIKA|VARALA SATHWIKA|VENGALAPURAM RAJU"
    },
    {
      c: "Inter 1st Year (BiPC)", b: "Inter 1st Year (BiPC)",
      n: "BADUGU GANGAJALA|BOLLAM HARIKA|DAVULA ARCHANA|GUNDOJE MANI DEEP|KAMBALA AKSHAYA|KANDLY SUJANI|KOTHAPELLY SHASWITHA|MAHESHUNI MANIDEEP|MAMIDI VAISHNAVI|MATHULAPURAM DIKSHITHA|PAPANAKA KEERTHANA|RANGU MANASHWINI|REGULA THRIVENI|SATHYAMANISH ERROJU|SINGIREDDY VAISHNAVI|THODETI HARSHITHA|VADLURI SAVEENA"
    },
    {
      c: "Inter 1st Year (CEC)", b: "Inter 1st Year (CEC)",
      n: "ADEPU SHRUTHI|AJMEERA SUSHANTH|ALAKUNTLA UPENDAR|ALLAM KAVYA|ARUKULLA SANKEERTHANA|BANDARI KAVITHA|BURRA MADHU|DANALA GOUTHAMI|DOMMATI NANDINI|EDLA SHIVAKUMAR|GARIGE BHARATH RAJ|ILAVENI SIRICHANDANA|JAKKULA ANITHYA|JANGILI ANANTHA SAHITH|KATUKOJWALA SAI SHIVA|KAVATI SRIJA|KOGILA AJAY|KOLIPAKA RISHIK VARDHAN|KYASA SAIPRIYA|MALA GANGA RAJU|MANDA SRINIDHI|MYAKALA CHARAN|NERUVATLA NAKSHATHRA|ORAM SAI CHARAN|PALUMARU ABHIRAM|PALUMARU ARCHANA|PANNALA BHARGAV|PATNURI SHIVAMANI|PULI POOJA|PURUSHOTHAM MANOGNA|RACHAKONDA RAMU|RACHARLA SANDEEP KUMAR|RAMADUGU MANI CHARAN|SAMPANGI DEVA KRUPA|SATTA AKHIL|SUTHRAPU RANADEEP|TADAGONDA NISHANTH|THODETI AKSHAYA|THOUTU NIKHIL|UTTAM SINDHU VARSHINI|VEYYIKANDLA AKSHAYA"
    },
    {
      c: "Inter 2nd Year (MPC)", b: "Inter 2nd Year (MPC)",
      n: "ADEPU RAM CHARAN|AILAVENI HARIKA|AKKENAPALLY LASYA|ALLAKONDA ASHWITHA|ARUKUTA ABHINAYA|BANDARI ANUSHA|BANDARI GAYATHRI|BANDARI RAJASHEKAR|BANDARI SHARATH|BANDI SAHITHYA|BEENAVENI SHARANYA|BHASA HANSIKA|BHEEMANAPALLY POOJA|BODDU AKSHITHA|CHELLOJI KARTHIK|CHEVULA PRAVALIKA|CHIPIRISHETTI MANASA|DUSA VAISHNAVI|ERROJU HARSHITHA|GANGADHARA SWAPNA|GOLLAPELLI SANJANA|GUNDLAPELLY MAHESHWARI|ITHARAVENI LOKESH|ITIKYALA VARSHITHA|KALLEM SHRAVYA|KELLETI SHIVANI|KOTHA SATHWIKA|KOYYADA SIRICHANDANA|KUNA RASMITHA|KUNCHE SATHWIKA|KUNTALA AKSHAY KUMAR|MANNE SOHANA|MASOORI MRUNALITHA|MOHAMMAD MUBHARAK|PADIRE KAVYA SRI|PALUMARU ANJANASOUMYA|PEDDOLLA KAVYA|PITTALA ARCHANA|REBBESH SREEJA|SANDUPATLA MANOJ|SIDDULA REKHA|SINGASANI PAVANTEJA|UPPU KALYANI|VELMULA LAHARI"
    },
    {
      c: "Inter 2nd Year (BiPC)", b: "Inter 2nd Year (BiPC)",
      n: "ADEPU ASHWITHA|AILENI MADHUSUDHAN|AITHARAVENI VAISHNAVI|AJMIRA NIHARIKA|BHUSARAPU VARSHATHVIKA|BOGA GREESHMIKA|BOGA RANI|BOGA VYSHNAVI|CHINTHAKINDI CHANDANA|DAVA MADHUSRI|EAGA PRANITHA|ELAGANDULA GLORY GRACE|ENUGULA SRIJA|ETTEM MAMATHA|GADARLA AKSHITHA|GANTYALA SPANDANA|ITHARAVENI AISHWARYA|KATAKAM SATWIKA|KOLAPURI HARSHINI|NARUKULLA HARIKA|NARUKULLA NADEEKSHA|NOONE RAMYA|PANCHITHA RISHWITHA|PATTEM SAGAR|RACHAKONDA BHAVANI|SATTA VARSHA|SUDHAVENI HIMASINDHU|SUDHAVENI PRASHAMSHA|SUNKE ANUSHA|TEEGALA AKSHITHA|YELPULA SHARANYA"
    },
    {
      c: "Inter 2nd Year (CEC)", b: "Inter 2nd Year (CEC)",
      n: "ARELLI ABHINAY|BAINA SAI KUMAR|BANDARI RAJU|BEENAVENI SIDDARTHA|BEJJANKI JYOTHSNA|BOLLAM HANSIKA|BOMMENA SATHWIK|CHEVULAMADDI MAHESH|DUSA SHASHANK|EDUMYAKALA RANJITH KUMAR|GADDAM SAI CHANDU|GAJJI HARSHAVARDHAN|GANGADHARA SAMANTHA|GUMMADI CHANDANA|JAMBULA SIGMA|JITTABOYINA SINDHU|KARABUJA SAHITHYA|KODURI SRIRAM|KOPPULA HARSHITH|KOTA GANESH|KOTA KARTHIK|KUNA AKHILA|KURUMALLA SANJANA|KYASA RAGHUNANDHAN|KYASA VARUN|KYASA VIJAY|MADDELA SATHISH KUMAR|MAGENI SAI KRISHNA|MAHANKALI CHARAN|MANKALI ARAVIND|MASKAM JASHWANTH|MUNJA SATHWIKA|NANDI RISHIK VARDAN|OLLEM MANASA|PALUMARU SHIVA|PULI MAHENDAR|PUNNAM VIGNESH|RAGALLA SHARANYA|SATTA BHAVYA|THADAGONDA TANUSH|THATIPARTHI VISHNUVARDHAN|THOTA SAI CHANDHU|THOTLA GOUTHAM KUMAR|THOUTU ANAND|UPPU MAHESH|UPPU MANIKANTA|UTTAM RASHMITHA|VEMULA MOUNIKA"
    }
  ];

  const result = [];
  data.forEach(group => {
    group.n.split('|').forEach(name => {
      result.push({ name: name.trim(), class: group.c, base: group.b });
    });
  });

  window.tgmsRawStudents = result;
})();
